language: go

go:
  - 1.8
  - master

install:
  - go get -d -v -t ./...
  - go get github.com/haya14busa/goverage

script:
  - go test -v -race ./...
  - go generate ./...
  - (! git diff | grep '^') # check diff
  - goverage -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
